### ISSUE TITLE
Build of meryl fails (sys/sysctl.h missing in gcc 7.5)

### ISSUE THREAD

**Issue by giesselmann** [marbl/Winnowmap#28]
Hi,

I tried building winnowmap on a linux 5.10 with gcc 7.5.0.
The winnowmap executable is build, but meryl fails. It is missing 'sys/sysctl.h'
`utility/src/utility/system.C:37:10: fatal error: sys/sysctl.h: No such file or directory
 #include <sys/sysctl.h>
          ^~~~~~~~~~~~~~
compilation terminated.
`

I could successfully build the master of https://github.com/marbl/meryl giving me a functional meryl binary.
I wonder if this will work, are there any version dependencies between winnowmap and meryl?

Thank you for your help,
Pay

**Comment by brianwalenz** [comment]
As far as I'm aware, there are no differences that should matter to winnowmap, but I'm not 100% sure.

The problem is that Linux 5.5 removed the sysctl() interface, but this version of meryl is still using it.  The latest version is not using it.

What distribution of Linux is that, out of curiosity?

**Comment by giesselmann** [comment]
Cool, thanks for the quick help, I'll use a standalone meryl then.
It's called Mariux, in-house build but somewhat ubuntu-like.

**Comment by cjain7** [comment]
Hi @giesselmann ,
Winnowmap code is also revised to have latest version of Meryl (commit: f9a4c1a). Please feel free to re-try and let us know if it works fine.

**Comment by giesselmann** [comment]
pulled, build, works.
Thank you!
